'model'
nvt-kts-12/backend pull request #1
Opened 2019-10-24 21:14 UTC by milosrasevic

2019-10-24 22:25 UTC, classicdocs requested changes
Ima 7 komentara

2019-10-24 22:25 UTC, classicdocs commented on src/main/java/nvt/kts/TicketApp/domain/model/event/Event.java
> +    @OneToMany
ovde treba da dodas (mappedBy = "event"), a u eventDay napravis atribut @ManyToOne Event event.. i onda ce on spojiti te table.. ovako ti sad imas u bazi bespotrebnu tabelu event_event_day..

2019-10-24 22:25 UTC, classicdocs commented on src/main/java/nvt/kts/TicketApp/domain/model/event/EventDay.java
> +    @OneToMany
Ista prica

2019-10-24 22:25 UTC, classicdocs commented on src/main/java/nvt/kts/TicketApp/domain/model/user/User.java
> +    @OneToMany
Ista prica sa mappedBy

2019-10-24 22:25 UTC, classicdocs commented on src/main/java/nvt/kts/TicketApp/domain/model/user/AbstractUser.java
> +public abstract class AbstractUser {
treba da extenduje AbstractEntity

2019-10-24 22:25 UTC, classicdocs commented on src/main/java/nvt/kts/TicketApp/domain/model/user/AbstractUser.java
> +    private Long id;
onda ovo obrisati

2019-10-24 22:25 UTC, classicdocs commented on src/main/java/nvt/kts/TicketApp/domain/model/location/Sector.java
> +    private int capacity;
mozda staviti @NotNull, jer treba i za parter i za tribinu popuniti kapacitet

2019-10-24 22:25 UTC, classicdocs commented on src/main/java/nvt/kts/TicketApp/domain/model/location/LocationScheme.java
> +    private List<Sector> sectors;
mappedBy

2019-10-25 18:56 UTC, milosrasevic commented on src/main/java/nvt/kts/TicketApp/domain/model/event/Event.java
> +    @OneToMany
ispravljeno

2019-10-25 18:56 UTC, milosrasevic commented on src/main/java/nvt/kts/TicketApp/domain/model/event/EventDay.java
> +    @OneToMany
ispravljeno

2019-10-25 18:57 UTC, milosrasevic commented on src/main/java/nvt/kts/TicketApp/domain/model/user/User.java
> +    @OneToMany
ispravljeno

2019-10-25 18:57 UTC, milosrasevic commented on src/main/java/nvt/kts/TicketApp/domain/model/user/AbstractUser.java
> +public abstract class AbstractUser {
ne moze da extenduje jer ide drugi generation type

2019-10-25 18:57 UTC, milosrasevic commented on src/main/java/nvt/kts/TicketApp/domain/model/user/AbstractUser.java
> +    private Long id;
ne brise se

2019-10-25 18:57 UTC, milosrasevic commented on src/main/java/nvt/kts/TicketApp/domain/model/location/Sector.java
> +    private int capacity;
stavljeno

2019-10-25 18:57 UTC, milosrasevic commented on src/main/java/nvt/kts/TicketApp/domain/model/location/LocationScheme.java
> +    private List<Sector> sectors;
ispravljeno

2019-10-25 19:01 UTC, merged